#  PARTSOLV.G: solution of linear systems by partitioned elimination

In [1]:
import numpy as np
import numpy.linalg as lin

In [2]:
modnum = np.array([4,3,2,1,2])

In [3]:
bet = 0.6

In [4]:
z = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18],[19,20,21],[22,23,24]])

In [5]:
z

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [6]:
m = 3
n = 6

In [7]:
pk = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]], ndmin=2)

In [8]:
pk

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [15]:
q22 = np.array([[2,4,-5],[0,2,-1],[0,0,1]])
q22

array([[ 2,  4, -5],
       [ 0,  2, -1],
       [ 0,  0,  1]])

In [18]:
q11 = np.array([[2,4,6,8,10,12,0,0],[0,2,4,6,8,10,12,0],[0,0,2,4,6,8,10,12]])
q11

array([[ 2,  4,  6,  8, 10, 12,  0,  0],
       [ 0,  2,  4,  6,  8, 10, 12,  0],
       [ 0,  0,  2,  4,  6,  8, 10, 12]])

In [19]:
def partsolv(z):
    y1 = z[0:m:,]
    y2 = z[m:n,]
    cy = np.shape(z)[1]
    cq = modnum[4]
    q21 = lin.solve((np.eye(n-m)-(q22*(bet*pk[m:n,0]).transpose())),np.concatenate([y2,(np.array([bet-np.sum((q22*(bet*pk[m:n,0]).transpose()).transpose(),axis=0)]).transpose())],axis=1))
    q12 = np.dot((q11[:,3:5]*(bet*pk[3:5,0]).transpose()), q21[0:cq])
    l = np.array([bet - np.sum((q11[:,1:m+cq]*(bet*pk[1:m+cq,0]).transpose()).transpose(),axis=0)]).T
    t = np.concatenate([np.array([q12[:,cy]]).transpose(),q11[:,1:m]*(bet*pk[1:m,0])], axis=1)
    t[:,0] = l[:,0] + t [:,0]
    y1 = lin.solve((np.eye(3)-t),(y1+q12[:,0:cy]))
    y2 = q21[:,0:cy]+np.array([q21[:,0+cy]]).T*y1[0,0:cy]
    return np.concatenate([y1,y2],axis=0)
    
    

In [20]:
partsolv(z)

array([[40.18850303, 42.68850303, 45.18850303],
       [40.23477568, 42.73477568, 45.23477568],
       [40.28104832, 42.78104832, 45.28104832],
       [39.91636689, 42.41636689, 44.91636689],
       [40.82446361, 43.32446361, 45.82446361],
       [40.2175035 , 42.7175035 , 45.2175035 ]])